version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: formations-db
    environment:
      POSTGRES_DB: FormationsDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: AA11..
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d FormationsDB"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./GestionFormationsBackend
      dockerfile: Dockerfile
    container_name: formations-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/FormationsDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=AA11..
      - JWT_SECRET=mysupersecretkeymysupersecretkeymysupersecretkeymysupersecretkey
      - CLOUDINARY_CLOUD_NAME=Root
      - CLOUDINARY_API_KEY=148692661576157
      - CLOUDINARY_API_SECRET=GSLzhhZsBJitJSns_K8ZqiyKW-Q
    ports:
      - "8080:8080"
    restart: always

  frontend:
    build:
      context: ./Gestion-formation---front
      dockerfile: Dockerfile
    container_name: formations-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
